// ═══ AGENT DEPARTMENTS ═══
// Seven real pharmaceutical departments, each an AI agent owning one stage of
// the opportunity funnel. A molecule flows top → bottom; every department says,
// in plain language: what it LOOKS FOR, the DATA it reads, what it RECEIVES from
// the prior department, and what it HANDS OFF to the next. This is the chain.

export const DEPARTMENTS = [
  {
    id: "scout",
    n: 1,
    name: "Lifecycle Management & Discovery",
    callsign: "Scout",
    role: "Repurposing & portfolio scan",
    glyph: "◎",
    color: "var(--entity-1)",
    colorHex: "#1a7fc1",
    dimension: null,
    eli5: "Finds every drug we have and every disease it could possibly treat.",
    looksFor: "A drug whose proven biology could treat another disease",
    reads: ["Molecule name & drug class", "ATC code", "Original approved use", "Known + emerging indications"],
    handoffIn: "— (start of pipeline: the raw portfolio)",
    handoffOut: "A drug × disease candidate to investigate",
  },
  {
    id: "cartographer",
    n: 2,
    name: "Regulatory Affairs & Intelligence",
    callsign: "Cartographer",
    role: "Global approval mapping",
    glyph: "▦",
    color: "var(--entity-3)",
    colorHex: "#009e73",
    dimension: "regulatory",
    eli5: "Checks where each use is ALREADY approved abroad — and where it is missing at home.",
    looksFor: "A use approved by a foreign regulator but missing in the home market",
    reads: ["Approval status across 20 regulators (FDA, EMA, PMDA…)", "Home market vs the rest of the world"],
    handoffIn: "Drug × disease candidate from Lifecycle Mgmt",
    handoffOut: "A confirmed regulatory gap + approval-breadth evidence",
  },
  {
    id: "clinician",
    n: 3,
    name: "Clinical Development & Medical Affairs",
    callsign: "Clinician",
    role: "Evidence & probability of success",
    glyph: "✚",
    color: "var(--entity-5)",
    colorHex: "#56b4e9",
    dimension: "evidence",
    eli5: "Reads the science: how strong is the proof, and what are the odds of approval?",
    looksFor: "How mature the clinical evidence is, and the probability of approval (PTRS)",
    reads: ["Trial phase (Preclinical → Phase IV)", "Phase-transition base rates by therapy area"],
    handoffIn: "Confirmed regulatory gap from Regulatory Affairs",
    handoffOut: "Probability of technical & regulatory success (PTRS) + evidence grade",
  },
  {
    id: "recon",
    n: 4,
    name: "Competitive Intelligence",
    callsign: "Recon",
    role: "Rival pipeline tracking",
    glyph: "⊙",
    color: "var(--entity-2)",
    colorHex: "#d55e00",
    dimension: "competitive",
    eli5: "Sees who else is racing for the same disease.",
    looksFor: "Other companies developing a drug for this same indication",
    reads: ["Competitor pipelines by indication", "Rival mechanisms & trial phases"],
    handoffIn: "Evidence-backed gap + PTRS from Clinical Development",
    handoffOut: "Competitive landscape + whitespace flag",
  },
  {
    id: "economist",
    n: 5,
    name: "Commercial & Market Access (HEOR)",
    callsign: "Economist",
    role: "Market sizing & unmet need",
    glyph: "▲",
    color: "var(--entity-4)",
    colorHex: "#cc79a7",
    dimension: "commercial",
    eli5: "Sizes the prize: how many patients, how valuable the markets, how unmet the need.",
    looksFor: "The patient population, market value, and severity of unmet need",
    reads: ["Global patient population", "Market-value index per country", "Unmet-need severity"],
    handoffIn: "Competitive landscape from Competitive Intelligence",
    handoffOut: "Commercial attractiveness signal",
  },
  {
    id: "risk",
    n: 6,
    name: "Portfolio Management & Decision Analytics",
    callsign: "Risk Officer",
    role: "Risk-adjusted prioritization",
    glyph: "◈",
    color: "var(--entity-6)",
    colorHex: "#e69f00",
    dimension: "ptrs",
    eli5: "Weighs odds, timing and competition into ONE honest, risk-adjusted score.",
    looksFor: "A single risk-adjusted score combining all seven factors",
    reads: ["All 7 dimension scores", "The weighting model"],
    handoffIn: "Commercial attractiveness signal from Market Access",
    handoffOut: "Composite score (0–99) + viability tier",
  },
  {
    id: "strategist",
    n: 7,
    name: "Business Development & Strategy",
    callsign: "Strategist",
    role: "Business case & recommendation",
    glyph: "★",
    color: "var(--brand-gold)",
    colorHex: "#d4a853",
    dimension: null,
    eli5: "Writes the one-page business case and ranks it against everything else.",
    looksFor: "What to do about it — and where it ranks across the whole portfolio",
    reads: ["The full scored profile", "All competing opportunities in the portfolio"],
    handoffIn: "Risk-adjusted composite score from Portfolio Management",
    handoffOut: "A ranked, actionable business case for the analyst desk",
  },
];

export const DEPARTMENT_BY_ID = Object.fromEntries(DEPARTMENTS.map(d => [d.id, d]));
