// ═══ AGENT DEPARTMENTS ═══
// The 7 "departments" of the autonomous swarm. Each is an AI agent that owns
// one stage of the opportunity funnel. The copy here is deliberately ELI5 —
// every analyst should understand at a glance what each agent does, what data
// it reads, and what it hands to the next agent down the line.
//
// Order matters: this IS the funnel. A molecule flows top → bottom.

export const DEPARTMENTS = [
  {
    id: "scout",
    n: 1,
    name: "Scout",
    role: "Discovery",
    glyph: "◎",
    color: "var(--entity-1)",
    colorHex: "#1a7fc1",
    dimension: null,
    eli5: "Finds every drug we have and every disease it could possibly treat.",
    question: "What could this drug be used for — everywhere in the world?",
    reads: ["Molecule name & drug class", "ATC code", "Original approved use", "Known + emerging indications"],
    outputs: ["A list of drug × disease candidates to investigate"],
  },
  {
    id: "cartographer",
    n: 2,
    name: "Cartographer",
    role: "Regulatory Gap Mapping",
    glyph: "▦",
    color: "var(--entity-3)",
    colorHex: "#009e73",
    dimension: "regulatory",
    eli5: "Checks where each use is ALREADY approved — and where it is missing.",
    question: "Is this use approved somewhere else but NOT in our home market?",
    reads: ["Approval status across 20 regulators (FDA, EMA, PMDA…)", "Home market vs the rest of the world"],
    outputs: ["The gap: approved abroad, open at home", "Breadth + regulatory-precedent scores"],
  },
  {
    id: "clinician",
    n: 3,
    name: "Clinician",
    role: "Evidence Review",
    glyph: "✚",
    color: "var(--entity-5)",
    colorHex: "#56b4e9",
    dimension: "evidence",
    eli5: "Reads the science. How strong is the proof the drug actually works here?",
    question: "How good is the clinical evidence, and what are the odds of approval?",
    reads: ["Trial phase (Preclinical → Phase IV)", "Phase-transition base rates by therapy area"],
    outputs: ["Evidence score", "PTRS — probability of approval, with confidence interval", "Time-to-approval estimate"],
  },
  {
    id: "recon",
    n: 4,
    name: "Recon",
    role: "Competitive Intel",
    glyph: "⊙",
    color: "var(--entity-2)",
    colorHex: "#d55e00",
    dimension: "competitive",
    eli5: "Sees who else is racing for the same disease.",
    question: "Are we alone here (whitespace), or is the field crowded?",
    reads: ["Competitor pipelines by indication", "Rival mechanisms & trial phases"],
    outputs: ["Competitor roster", "Whitespace flag", "Competitive score"],
  },
  {
    id: "economist",
    n: 5,
    name: "Economist",
    role: "Commercial Sizing",
    glyph: "▲",
    color: "var(--entity-4)",
    colorHex: "#cc79a7",
    dimension: "commercial",
    eli5: "Sizes the prize: how many patients, how valuable the markets.",
    question: "How big is this opportunity in dollars and patients?",
    reads: ["Global patient population", "Market-value index per country", "Unmet-need severity"],
    outputs: ["Commercial score", "Unmet-need score", "Addressable-market signal"],
  },
  {
    id: "risk",
    n: 6,
    name: "Risk Officer",
    role: "Risk & Scoring",
    glyph: "◈",
    color: "var(--entity-6)",
    colorHex: "#e69f00",
    dimension: "ptrs",
    eli5: "Weighs odds, timing and competition into ONE honest score.",
    question: "Once everything is weighed, how good is this opportunity, really?",
    reads: ["All 7 dimension scores", "Weighting model"],
    outputs: ["Composite score (0–99)", "Viability tier: Excellent / Strong / Moderate / Low"],
  },
  {
    id: "strategist",
    n: 7,
    name: "Strategist",
    role: "Business Case",
    glyph: "★",
    color: "var(--brand-gold)",
    colorHex: "#d4a853",
    dimension: null,
    eli5: "Writes the one-page business case and ranks it against everything else.",
    question: "What should we DO about it — and where does it rank?",
    reads: ["The full scored profile", "All competing opportunities in the portfolio"],
    outputs: ["Ranked business case", "Recommended action", "Plain-English rationale"],
  },
];

export const DEPARTMENT_BY_ID = Object.fromEntries(DEPARTMENTS.map(d => [d.id, d]));
