// ═══ PHASE 2 — CALIBRATION / BACKTEST HARNESS ═══
// Scores the model's predicted probability of regulatory success (PTRS) against
// the labelled outcomes available in the VERIFIED slice, and reports Brier score
// + Expected Calibration Error (ECE) with a binned reliability table.
//
// HONEST CAVEAT: the verified slice is dominated by APPROVED indications
// (outcome=1), so this measures the methodology + surfaces label skew — it is
// NOT yet a balanced backtest. A real calibration needs failed/withdrawn
// programs too. This harness is the scaffold to run that once such data exists.
//
//   node scripts/calibrate.mjs   →  writes CALIBRATION.md
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DATA = path.join(ROOT, "src", "lib", "data");

const { COMPANIES } = await import(pathToFileURL(path.join(DATA, "companies.js")).href);
const { generateIndicationData } = await import(pathToFileURL(path.join(DATA, "indications.js")).href);
const { calculatePTRS } = await import(pathToFileURL(path.join(DATA, "ptrs.js")).href);

// Collect unique verified (molecule, indication) rows with their TA.
const seen = new Set();
const samples = [];
for (const c of COMPANIES) for (const m of c.molecules) {
  for (const ind of generateIndicationData(m)) {
    if (ind.confidence !== "verified") continue;
    const key = `${m.name}::${ind.indication}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const predicted = calculatePTRS(ind.evidence, m.ta).ptrs;
    const outcome = (ind.countries && ind.countries.length > 0) ? 1 : 0; // approved somewhere = success
    samples.push({ mol: m.name, indication: ind.indication, ta: m.ta, evidence: ind.evidence, predicted, outcome });
  }
}

const n = samples.length;
const brier = n ? samples.reduce((s, x) => s + (x.predicted - x.outcome) ** 2, 0) / n : NaN;
const meanPred = n ? samples.reduce((s, x) => s + x.predicted, 0) / n : NaN;
const baseRate = n ? samples.reduce((s, x) => s + x.outcome, 0) / n : NaN;

// 10-bin reliability + ECE.
const B = 10;
const bins = Array.from({ length: B }, () => ({ n: 0, sumP: 0, sumO: 0 }));
for (const x of samples) {
  const bi = Math.min(B - 1, Math.floor(x.predicted * B));
  bins[bi].n++; bins[bi].sumP += x.predicted; bins[bi].sumO += x.outcome;
}
let ece = 0;
const rows = bins.map((b, i) => {
  const lo = (i / B).toFixed(1), hi = ((i + 1) / B).toFixed(1);
  const conf = b.n ? b.sumP / b.n : 0, acc = b.n ? b.sumO / b.n : 0;
  if (b.n) ece += (b.n / n) * Math.abs(acc - conf);
  return { range: `${lo}–${hi}`, n: b.n, conf, acc };
});

const md = `# ExpandRx — Calibration Report

**Generated by** \`scripts/calibrate.mjs\` over the source-verified slice.

## Summary
| Metric | Value |
|---|---|
| Labelled samples (verified rows) | ${n} |
| Base rate (approved somewhere) | ${(baseRate * 100).toFixed(1)}% |
| Mean predicted PTRS | ${(meanPred * 100).toFixed(1)}% |
| **Brier score** (lower = better) | **${brier.toFixed(4)}** |
| **Expected Calibration Error (ECE)** | **${(ece * 100).toFixed(1)}%** |

## Reliability table (predicted vs observed)
| Predicted bin | n | Mean predicted | Observed approved |
|---|---|---|---|
${rows.filter(r => r.n > 0).map(r => `| ${r.range} | ${r.n} | ${(r.conf * 100).toFixed(0)}% | ${(r.acc * 100).toFixed(0)}% |`).join("\n")}

## Honest interpretation
- The verified slice is **outcome-skewed** (base rate ${(baseRate * 100).toFixed(0)}% — most verified indications are already approved somewhere), so this run principally **validates the harness and the methodology**, not a balanced predictive backtest.
- A meaningful calibration requires **negative labels** (failed, withdrawn, or never-approved programs) at comparable volume. The harness computes Brier + ECE the moment such labelled data is added to the verified slice.
- Roadmap: extend the verified-data pipeline (per \`HANDOFF.md\` Phase 1) to capture failed/terminated programs (ClinicalTrials.gov terminated status, FDA CRLs) so PTRS can be calibrated against ground truth and the reliability table becomes decision-grade.

_Re-run: \`node scripts/calibrate.mjs\`._
`;

fs.writeFileSync(path.join(ROOT, "CALIBRATION.md"), md);
console.log(`── CALIBRATION ──\n  samples ${n} | baseRate ${(baseRate * 100).toFixed(1)}% | Brier ${brier.toFixed(4)} | ECE ${(ece * 100).toFixed(1)}%`);
console.log("  wrote CALIBRATION.md");
